credentials_file_path = "C:/Users/falgu/AppData/Roaming/gcloud/application_default_credentials.json"
project_id = "gcpplayground-433406"
project_number = "608273188096"
project_suffix = "gcpplay"
region = "us-central1"
multiregion = "us"