credentials_file_path = "C:/Users/falgu/AppData/Roaming/gcloud/application_default_credentials.json"
project_id = "industrial-keep-410516"
project_number = "321560073577"
region = "us-central1"
multiregion = "us"