dagTimeout: 1200s
jobs:
  - sparkJob:
      jarFileUris:
        - https://storage.cloud.google.com/aleix-tmp-bucket/GcpPlayground-assembly-0.1.0-SNAPSHOT.jar
      mainClass: dataproc.Demo1
      properties:
        spark.driver.cores: "2"
        spark.driver.memory: "4G"
        spark.executor.instances: "2"
        spark.executor.memory: "4G"
        spark.executor.cores: "4"
        spark.dynamicAllocation.enabled: "false"
    stepId: compute
placement:
  managedCluster:
    clusterName: 'ephemeral-spark-cluster'
    config:
      configBucket: gs://aleix-stg-bucket
      tempBucket: gs://aleix-tmp-bucket
      gceClusterConfig:
        internalIpOnly: true
        subnetworkUri: 'us-central1'
      softwareConfig:
        imageVersion: 2.0.56-debian10
      masterConfig:
        numInstances: 1
        machineTypeUri: 'n1-standard-4'
      workerConfig:
        numInstances: 2
        machineTypeUri: 'n1-standard-4'