name: Dataproc Demo1

on:
  push:
    branches: ["feature/dataproc/demo1"]

permissions:
  contents: read

env:
  PROJECT_ID: industrial-keep-410516

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run sbt clean compile assembly
      run: sbt clean compile assembly

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_email: ${{ secrets.GCP_GCS_SA_DEMOS_EMAIL }}
        service_account_key: ${{ secrets.GCP_GCS_SA_DEMOS_KEY }}
        project_id: ${{ env.PROJECT_ID }}
      
    - name: Upload jar to GCS
      run: gsutil -m cp .\target\scala-2.13\GcpPlayground-assembly-0.1.0-SNAPSHOT.jar gs://aleix-demos-bucket/dataproc/demo1/jars/
