name: Dataproc Demo1

on:
  push:
    branches: ["feature/dataproc/demo1"]

permissions:
  contents: read

env:
  PROJECT_ID: industrial-keep-410516
  JAR_NAME: GcpPlayground-assembly-0.1.0-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_GCS_SA_DEMOS_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run sbt clean compile assembly
      run: sbt clean compile assembly

    - name: Upload jar to GCS
      run: |
        gsutil -m cp ./target/scala-2.13/${{ env.JAR_NAME }} gs://aleix-demos-bucket/dataproc/demo1/jars/
