name: Run Dataproc with a workflow-template file

on:
  workflow_call:
    inputs:
      region:
        description: 'Region'
        required: true
        type: string
      workflow_template_path:
        description: 'Workflow file path'
        required: true
        type: string
      workflow_template_id:
        description: 'Workflow template id'
        required: true
        type: string
      spark_history_bucket:
        description: 'Spark History bucket path'
        required: true
        type: string
      custom_sed:
        description: 'Custom workflow template sed'
        required: false
        type: string

permissions:
  contents: read
  
env:
  SPARK_HISTORY_PATH: ${{ inputs.spark_history_bucket }}/${{ inputs.workflow_template_id }}

jobs:
  deploy_on_dataproc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEMOSSAK }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Init spark history logs folders in GCS
        run: |
          sh ./src/main/resources/bin/init_GCS_folder.sh ${{ env.SPARK_HISTORY_PATH }}/spark-job-history
          sh ./src/main/resources/bin/init_GCS_folder.sh ${{ env.SPARK_HISTORY_PATH }}/yarn-logs

      - name: Custom workflow template sed
        if: inputs.custom_sed != ''
        run: sed -i '${{ inputs.custom_sed }}' ${{ inputs.workflow_template_path }}

      - name: Set clusterName and spark history folder path (clusterName = spark history folder path = workflow template ID)
        run: | 
          sed -i 's/@@CLUSTER_NAME/${{ inputs.workflow_template_id }}/g; s|@@SPARK_HISTORY_PATH|${{ env.SPARK_HISTORY_PATH }}|g' ${{ inputs.workflow_template_path }}

      - name: Run dataproc import
        run: |
          gcloud dataproc workflow-templates import ${{ inputs.workflow_template_id }} --region=${{ inputs.region }} --source=${{ inputs.workflow_template_path }} --quiet

      - name: Run dataproc instantiate
        run: |
          gcloud dataproc workflow-templates instantiate ${{ inputs.workflow_template_id }} --region=${{ inputs.region }}