name: SparkExercicesEtl

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build before run workflow'
        required: true
        type: boolean
        default: false
permissions:
  contents: read

jobs:
  call-build-workflow:
    if: inputs.build == true
    uses: ./.github/workflows/build.yaml
    with:
      deploy: true
    secrets: inherit

  call-run-dataproc-with-wt-workflow:
    needs: call-build-workflow
    if: always()
    uses: ./.github/workflows/run_dataproc_with_wt.yaml
    with:
      region: us-central1
      workflowTemplateFilePath: ./src/main/resources/dataproc/SparkExercicesEtl_wt.yaml
      workflowTemplateId: spark-exercices-etl
      sparkHistoryBucket: spark-history-bucket
    secrets: inherit
