name: Tmp SparkExercicesEtl

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      build:
        description: 'Build before run workflow'
        required: true
        type: boolean
        default: false
      etl:
        description: 'ETL to execute'
        required: true
        type: choice
        options:
          - products
          - sellers
          - sales
          - all
        default: products

permissions:
  contents: read

env:
  WORKFLOW_TEMPLATE_FILE_PATH: ./src/main/resources/dataproc/SparkExercicesEtl_wt.yaml

jobs:
  call_build_workflow:
    if: inputs.build == true
    uses: ./.github/workflows/build.yaml
    with:
      deploy: true
    secrets: inherit

  call_run_dataproc_with_wt_workflow:
    needs: call_build_workflow
    if: always()
    uses: ./.github/workflows/run_dataproc_with_wt.yaml
    with:
      region: us-central1
      workflow_template_file_path: ./src/main/resources/dataproc/SparkExercicesEtl_wt.yaml
      workflow_template_id: spark-exercices-etl
      spark_history_bucket: spark-history-bucket
      custom_sed: s/@@ETL/products/g;
    secrets: inherit
